on:
  push:
    branches: [master]
  workflow_dispatch:

name: Bun Test
jobs:
  run-dev:
    name: Run Dev Server
    runs-on: ubuntu-latest
    steps:
      # Checkout the code again
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Run bun run dev in the background and stop after 3 seconds
      - run: |
          cd frontend
          bun install  # Install dependencies for frontend
          cd ..
          cd backend
          bun install  # Install dependencies for backend
          cd ..
          bun run dev &
          sleep 3
          kill $!

  run-build:
    name: Run Build
    runs-on: ubuntu-latest
    needs: run-dev
    steps:
      # Checkout the code again
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Run bun run build
      - run: |
          cd frontend
          bun install  # Install dependencies for frontend
          cd ..
          cd backend
          bun install  # Install dependencies for backend
          cd ..
          bun run build

  run-start:
    name: Run Start Server
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      # Checkout the code again
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Run bun run start in the background and stop after 3 seconds
      - run: |
          cd frontend
          bun install  # Install dependencies for frontend
          cd ..
          cd backend
          bun install  # Install dependencies for backend
          cd ..
          bun run start &
          sleep 3
          kill $!
