on:
  push:
    branches: [master]
  workflow_dispatch:

name: Bun Test
jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Install dependencies in frontend
      - run: |
          cd frontend
          bun install

      # Install dependencies in backend
      - run: |
          cd backend
          bun install

  run-dev:
    name: Run Dev Server
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      # Checkout the code again since each job is isolated
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Run bun run dev in the background and stop after 3 seconds
      - run: |
          cd frontend
          bun run dev &
          sleep 3
          kill $!

  run-build:
    name: Run Build
    runs-on: ubuntu-latest
    needs: run-dev
    steps:
      # Checkout the code again
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Run bun run build
      - run: |
          cd frontend
          bun run build

  run-start:
    name: Run Start Server
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      # Checkout the code again
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Run bun run start in the background and stop after 3 seconds
      - run: |
          cd frontend
          bun run start &
          sleep 3
          kill $!
